server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-movies
          uri: lb://service-movies
          predicates:
            - Path=/store/v1/movies/**
        - id: service-showtime
          uri: lb://service-showtime
          predicates:
            - Path=/store/v1/showtime/**
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/store/v1/users/**
        - id: service-bookings
          uri: lb://service-bookings
          predicates:
            - Path=/store/v1/bookings/**
